### ISSUE TITLE
Display folder sizes.

### ISSUE THREAD

**Issue by pkgodara** [harshjv/github-repo-size#19]
It would be great if it displays folder sizes also. Would be great for big projects as they have lots of folders/extensions and could easily track their sizes.

**Comment by stevennoto** [comment]
I believe this could be done by using the GitHub `git/trees` API, which has a recursive mode, which would allow gathering size data for subfolders. For example: https://api.github.com/repos/harshjv/github-repo-size/git/trees/master?recursive=1

Since it's Hacktoberfest, I'll take a look at this, it might be a simple change.

**Comment by harshjv** [comment]
@stevennoto Sorry, I was busy with work! I've left a comment on your PR! Let me know what you think. :)

**Comment by harshjv** [comment]
Please read this comment https://github.com/harshjv/github-repo-size/pull/26#issuecomment-340170239

**Comment by stevennoto** [comment]
Hi @harshjv, thanks for replying so quickly, and great points on the PR. I did some testing but not on anything as large as node! I like the idea of making it optional/on demand. I also wonder if it's possible to cache the results, since the `trees` API returns the entire repo tree at once.

I'll probably play with these ideas, and revise the PR.

**Comment by dmwyatt** [comment]
@stevennoto Any progress?

**Comment by stevennoto** [comment]
Hi @dmwyatt. If you look at the linked PR (#32), I have a version that addresses these concerns and seems to work well. The maintainer will review it when there's a chance.

In the meantime, if you'd like to try out that version, you can follow the instructions in https://github.com/harshjv/github-repo-size#development (with the extra step of checking out my branch). Thanks!
